services:
  - type: web
    name: healthcare-feedback-portal-backend
    env: node
    buildCommand: npm install
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
