services:
  - type: web
    name: healthcare-feedback-portal-backend
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
